# TODO: this package should be marked as conflicting with pgplot.

{% set name = 'giza' %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/{{ name }}/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 69f6b8187574eeb66ec3c1edadf247352b0ffebc6fc6ffbb050bafd324d3e300
  patches:
    - fix-tests.patch
    - disable-macos-tests.patch  # [osx]

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - make
    - pkg-config
    - {{ compiler("fortran") }}
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - pthread-stubs
    - cairo
    - xorg-xorgproto
    - xorg-libice
    - xorg-libsm
    - xorg-libx11
    - xorg-libxext
    - xorg-libxrender
    - liblzma-devel
    # needed for pkg-config files:
    - expat
    - zlib

test:
  # note: most tests are run in build.sh
  commands:
    - test -e $PREFIX/lib/libgiza$SHLIB_EXT
    - test -e $PREFIX/lib/libpgplot$SHLIB_EXT
    - test -e $PREFIX/lib/libcpgplot$SHLIB_EXT

about:
  home: http://giza.sourceforge.net/
  license: GPL-2.0-only
  license_file: COPYING
  summary: A drop-in replacement for PGPLOT using C and Cairo.

extra:
  recipe-maintainers:
    - pkgw
