# TODO: this package should be marked as conflicting with pgplot.

{% set name = 'giza' %}
{% set version = "0.9.5" %}
{% set sha256 = "0151be118d8249161b1bc547ef4dd5f28f6340106f1e209e71ad8a0b6617b7b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - fix-tests.patch
    - disable-macos-tests.patch  # [osx]

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - pkg-config
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - pthread-stubs
    - cairo
    - xorg-libice 1.0.*
    - xorg-libsm 1.2.*
    - xorg-libx11 1.6.*
    - xorg-libxext 1.3.*
    - xorg-libxrender 0.9.*
    - xz
  run:
    - cairo
    - xorg-libice 1.0.*
    - xorg-libsm 1.2.*
    - xorg-libx11 1.6.*
    - xorg-libxext 1.3.*
    - xorg-libxrender 0.9.*
    - xz

test:
  # note: most tests are run in build.sh
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - test -e $PREFIX/lib/libgiza$SHLIB_EXT
    - test -e $PREFIX/lib/libpgplot$SHLIB_EXT
    - test -e $PREFIX/lib/libcpgplot$SHLIB_EXT

about:
  home: http://giza.sourceforge.net/
  license: GPLv2
  license_file: COPYING
  summary: A drop-in replacement for PGPLOT using C and Cairo.

extra:
  recipe-maintainers:
    - pkgw
