travis:
  secure:
    BINSTAR_TOKEN: IH1FXwybfR6hMv9K4W0Sq8cUzNFLmbV8yJ78KnmfNCBh6cuBuR6kLgMCgvax894ahlDYblWrdeff8/lOhy+vrRIwVeKraeBRhGmc3XlaklXdSnqAtKwJU1P9v9TpbuKMYanZBuBm8pFKbn2xU6cr40Qh9eJPjiqgbH+okXYQxAalZySBmHkFrTjvbTQ7L3PyaabvsGua8Mri5rUbMECpvycJu2ArLI1tMI1B7iqo8HWY4qXprYbMpPoZFwnHogDcgD/rhlIgkmIXqBAGd6fSoMxQqKVl8eVo3J8Y2WU1v0SW2xHRqA6mtlmnhBLJHCr1AKitVuf4eV36qMW5eT7VuSnIvT3FtiMuKnIAT4ZG225Hek0nH3XpnmzyNGd7UqgBmZJAbwQp4fRszP70tq7z1Wbn7MX4VBSOLAnBgExxsLebTHmVlZ2JpdwPoQSTKiPjx0AzUUIcSoBFw7cmD2fiR8KtBbnspZIyIr3H7TeA835AZT4lXki55dRxR1hVTDL5TFfyW1XLexHFqtJA+TEpeaPGJvG6KerTCQQH4KdKwUOtA+A12DbJV2EKZVZEnPPTuwWkgZ/UIllcjZo1YT4KJBdh1Gj6woJ3ZAmy/j6xvhYNSj6XR9AIdOB0N2Vl7ZqsR3NhsHd5xZItg/U21aIGVSgrwlRNEuFfV32382ZGtOc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
