travis:
  secure:
    BINSTAR_TOKEN: KWRyaqv8GJQvvrKlAp9Y/VR1UpJu0DSymOs5Te6adp7PyhOYefz14NgYsc6xif6qrPSG119l4N1cq6zK/6y2v7fdWAmi3H6NQ6S6Wz73d6jMKqhhEO1hWMMXXGOfR0ieJvqciJByDyy3h/Su4CugLp9ir302sn5tr4aR+VIlZ1zKCQoq6U1kYuUnKpYbF5A0XfhPXNROAU1nfXEzuiHRK+fCmZ72Kyxc1Z4sIQKTIG3hfeZBJZU/xE/BYSHNI/OY7d2K5XOlBaVFb7B2PhHMB0xwf0wabiVfSOJDKwyAQLzP3QyR27EiQDGcP8N99S2zJTrrIdmcoG9iqfzFIh0k4NvQFxdu9sud5kySagCfQFTqvmrd58w+XvI9/6heldhv5orgIqTKqwTDlIyjRIO6EIu2n1yhazp23XK+iRypdmqawjxRVojIx+k4j/8IyJVhsWi6neMc72dcUExp8baCOShNmyK3X+EvxiqpMyOdH7MVepCNQwk5KmbeMDZnqFV21/LqAUiGihGd4PC4aPZ1Vdb4VJba06hUxvT8KuSoRl7ArpZkgKmUqZYs+2JmBDLDTxxQQBxAHKx9yfCWpKsHaIAhdHEVrWu3yXmjPTqfwfQ36Fb6/+xNjScsqT2RR3DXPQ5kgq9zoTHxWToZ5AM3NethsiRuJdzWPhxf9Ubuzfk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
